### ISSUE TITLE
为什么在禁用Euphony后，LL无法加载了

### ISSUE THREAD

**Issue by LINKlang** [xtaw/LiteLoaderQQNT-Euphony#3]
来自一个非开发者的问题
在我禁用Euphony后，所有的插件和liteloader都无法启用了

https://github.com/xtaw/LiteLoaderQQNT-Euphony/assets/116951234/a382664e-2b84-42cf-bd07-bc2dee663a06

**Comment by adproqwq** [comment]
文本转语音 插件依赖 Euphony 插件，你禁用了，它找不到依赖项，就会导致整个ll报错
